# -*- coding: utf-8 -*-
"""Acquiring and processing information on world's largest banks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfmExhhUyyx2kiSqi5UGsEdflGDyl1B4
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import sqlite3
from datetime import datetime

url = "https://web.archive.org/web/20230908091635/https://en.wikipedia.org/wiki/List_of_largest_banks"
csv_exchange_rate = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMSkillsNetwork-PY0221EN-Coursera/labs/v2/exchange_rate.csv"
table_attribs = ["Name", "MC_USD_Billion"]
output_csv_path = "./Largest_banks_data.csv"
db_name = "Banks.db"
table_name = "Largest_banks"
log_file = "code_log.txt"

# Code for ETL operations on Country-GDP data

# Importing the required libraries

def log_progress(message):
    ''' This function logs the mentioned message of a given stage of the
    code execution to a log file. Function returns nothing'''

def extract(url, table_attribs):
    ''' This function aims to extract the required
    information from the website and save it to a data frame. The
    function returns the data frame for further processing. '''

    return df

def transform(df, csv_path):
    ''' This function accesses the CSV file for exchange rate
	information, and adds three columns to the data frame, each
	containing the transformed version of Market Cap column to
	respective currencies'''

    return df

def load_to_csv(df, output_path):
    ''' This function saves the final data frame as a CSV file in
	the provided path. Function returns nothing.'''

def load_to_db(df, sql_connection, table_name):
    ''' This function saves the final data frame to a database
	table with the provided name. Function returns nothing.'''

def run_query(query_statement, sql_connection):
    ''' This function runs the query on the database table and
    prints the output on the terminal. Function returns nothing. '''

''' Here, you define the required entities and call the relevant
functions in the correct order to complete the project. Note that this
portion is not inside any function.'''

# Task 1
def log_progress(message):
    now = datetime.now()
    timestamp_format = '%Y-%b-%d-%H:%M:%S'
    timestamp = now.strftime(timestamp_format)
    with open(log_file, "a") as f:
        f.write(f"{timestamp} : {message}\n")

# Task 2
def extract(url, table_attribs):
    page = requests.get(url).text
    data = BeautifulSoup(page, 'html.parser')
    data_list = []

    tables = data.find_all('tbody')
    rows = tables[1].find_all('tr')

    for row in rows:
        col = row.find_all('td')
        if len(col) != 0:
            if len(col[1].find_all('a')) > 1:
                bank_name = col[1].find_all('a')[1].contents[0]
            else:
                bank_name = col[1].text.strip()

            market_cap_str = col[2].text.rstrip('\n').strip().replace(',', '')
            market_cap = float(market_cap_str)

            data_dict = {
                "Name": bank_name,
                "MC_USD_Billion": market_cap
            }
            data_list.append(data_dict)

    df = pd.DataFrame(data_list, columns=table_attribs)
    return df

# Task 3
def transform(df, csv_path):

    dataframe_exchange = pd.read_csv(csv_path)
    exchange_rate = dataframe_exchange.set_index('Currency').to_dict()['Rate']

    gbp_rate = float(exchange_rate['GBP'])
    eur_rate = float(exchange_rate['EUR'])
    inr_rate = float(exchange_rate['INR'])

    df['MC_GBP_Billion'] = [np.round(x * gbp_rate, 2) for x in df['MC_USD_Billion']]
    df['MC_EUR_Billion'] = [np.round(x * eur_rate, 2) for x in df['MC_USD_Billion']]
    df['MC_INR_Billion'] = [np.round(x * inr_rate, 2) for x in df['MC_USD_Billion']]

    return df

# Task 4: CSVファイル格納関数
def load_to_csv(df, output_path):
    df.to_csv(output_path, index=False)

df_transformed = transform(df_extracted, csv_exchange_rate)

log_progress("Data transformation complete. Initiating Loading process")

print(df_transformed)

# Direct dictionary call variant
df['MC_GBP_Billion'] = [np.round(x * float(exchange_rate['GBP']), 2) for x in df['MC_USD_Billion']]

print(df['MC_EUR_Billion'][4])

# Taks 4
def load_to_csv(df, output_path):
    df.to_csv(output_path, index=False)

# Task 5
def load_to_db(df, sql_connection, table_name):
    df.to_sql(table_name, sql_connection, if_exists='replace', index=False)

conn = sqlite3.connect("Banks.db")

# 2. テーブル一覧を取得して表示（テーブルが作られているかの確認）
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("--- データベース内のテーブル一覧 ---")
print(tables)

# 3. データの最初の5行を引っ張ってきて表示（データが注入されているかの確認）
print("\n--- Largest_banks テーブルのデータ（先頭5行） ---")
df_check = pd.read_sql("SELECT * FROM Largest_banks LIMIT 5", conn)
print(df_check)

# 接続を閉じる
conn.close()

# Task 6
def run_query(query_statement, sql_connection):
    ''' This function runs the query on the database table and prints the output on the terminal. '''
    # Print the query statement along with the output
    print(f"Query Statement: {query_statement}\n")

    # Generate the output of the query using Pandas
    query_output = pd.read_sql(query_statement, sql_connection)
    print(query_output)
    print("-" * 50)

# Define the second query statement as mentioned in the project scenario
query_2 = "SELECT AVG(MC_GBP_Billion) FROM Largest_banks"

# Execute the function call
run_query(query_2, sql_connection)

# Define the third query statement as mentioned in the project scenario
query_3 = "SELECT Name FROM Largest_banks LIMIT 5"

# Execute the function call
run_query(query_3, sql_connection)

# Close the SQLite3 database connection as per the project workflow
sql_connection.close()

# Make the final relevant log entry exactly as specified in the instructions table
log_progress("Server Connection closed")

# 💡 古いログを一度削除して、完全にクリーンな状態からスタートします
!rm -f code_log.txt

# 1. 開始メッセージ (表示されていた行)
log_progress("Preliminaries complete. Initiating ETL process")

# 2. Extract 実行 & ログ
df_extracted = extract(url, table_attribs)
log_progress("Data extraction complete. Initiating Transformation process")

# 3. Transform 実行 & ログ
df_transformed = transform(df_extracted, csv_exchange_rate)
log_progress("Data transformation complete. Initiating Loading process")

# 4. Load to CSV 実行 & ログ
load_to_csv(df_transformed, output_csv_path)
log_progress("Data saved to CSV file")

# 5. SQL 接続 & ログ
sql_connection = sqlite3.connect(db_name)
log_progress("SQL Connection initiated")

# 6. Load to DB 実行 & ログ
load_to_db(df_transformed, sql_connection, table_name)
log_progress("Data loaded to Database as a table, Executing queries")

# 7. クエリ実行 & ログ (3つのクエリを連続実行)
run_query("SELECT * FROM Largest_banks", sql_connection)
run_query("SELECT AVG(MC_GBP_Billion) FROM Largest_banks", sql_connection)
run_query("SELECT `Name` FROM Largest_banks LIMIT 5", sql_connection)
log_progress("Process Complete")

# 8. 接続クローズ & 最終ログ
sql_connection.close()
log_progress("Server Connection closed")

print("--- すべてのETL処理と8つのログ書き込みが完了しました！ ---")

